### PR TITLE
updated metadata

### PR DESCRIPTION
**Pull request by bmcfee**
- Fixed links to point to the org url

### CODE REVIEW

**Comment by jakirkham** [comment]
Please fork @bmcfee. If you don't fork, it will try to deploy packages in your PR before merging.

**Comment by bmcfee** [comment]
Aha, derp!  Sorry, I didn't realize that.  Thanks.

**Comment by jakirkham** [comment]
Also, for updating metadata the proper way to do that is update the recipe and then run `conda smithy rerender` and commit all changes. To get `conda-smithy`, run `conda install -n root conda-smithy`. Also, I've seen some issues with `conda-build-all` version `0.13.0` so you may want to install `0.12.0` instead. That also goes in the `root` environment.

**Comment by jakirkham** [comment]
Fortunately there is no build number bump here so you should be ok on the deployment front. Just wanted to make you aware of that.

**Comment by jakirkham** [comment]
Have you tried with `conda smithy rerender`? I expect the results will be the same, but it is good to get experience with it as it is a very powerful tool.

**Pull request closed without merging**
