### PR TITLE
Add tarball for Python 3.7

### PR DESCRIPTION
**Pull request by tats-u**
I'm bothered from the issue Librosa, which depends on this package, obstructs me from keeping using Python 3.7 and make my Python downgrade to 3.6.

I looked into the dependency and found out that this package does not support 3.7.

### CODE REVIEW

**Comment by tats-u** [comment]
This seems to be the problem of not only this package but also conda-forge.  ~~I suspend this issue and will reopen someday.~~

I suppose this PR is required someday and do not have to be closed.

**Comment by tats-u** [comment]
https://www.appveyor.com/docs/windows-images-software/#miniconda

Miniconda3 4.5.11 (Python 3.7.0): C:\Miniconda36 or C:\Miniconda3
Miniconda3 4.5.11 x64 (Python 3.7.0): C:\Miniconda36-x64 or C:\Miniconda3-x64
:thinking:

**Comment by jakirkham** [comment]
Would recommend re-rendering and then rebasing these changes on the re-rendered feedstock.

ref: https://conda-forge.org/docs/webservice.html#conda-forge-admin-please-rerender

**Comment by tats-u** [comment]
@jakirkham 🆋
@conda-forge-admin, please rerender

**Comment by tats-u** [comment]
Oh no, settings for Python 3.7 went away🤯

**Comment by tats-u** [comment]
I suppose @ conda-forge-admin and build system don't support Python 3.7 and I'm powerless to this issue.

**Comment by jakirkham** [comment]
So you can still rebase your old changes on top of it. Was thinking the re-rendering could go in a different PR to simplify the process a bit.

**Comment by tats-u** [comment]
It seems that `conda-forge::conda-forge-ci-setup=2` does not support Python 3.7.  It downgrades Python to 3.6.

**Comment by jakirkham** [comment]
That downgrade is only occurring in `root`; not the build environment. So it doesn't concern us.

**Comment by tats-u** [comment]
Oh, Python 3.7 is really installed in the build environments.

**Comment by tats-u** [comment]
Thre is no configuration for 32bit Windows Python.  Is it right?

**Comment by jakirkham** [comment]
We did a survey of users a while back and determined that there were not enough users on Windows 32-bit to justify supporting that platform further. So it was dropped.

**Comment by tats-u** [comment]
I got it.  Are there remaining problems to be fixed with my changes?

**Comment by mfansler** [comment]
Closing as stale.

**Pull request closed without merging**
